const PAGES = {
  LOGIN: 'LOGIN_PAGE',
  REGISTER: 'REGISTER_PAGE',
  CSV_CONFIG: 'CSV_CONFIG_PAGE',
  BLUETOOTH_CONFIG: 'BLUETOOTH_CONFIG_PAGE',
  ROOM_LIST: 'ROOM_LIST_PAGE',
  ROOM_DETAIL: 'ROOM_DETAIL_PAGE',
  ROOM_SCANNING: 'ROOM_SCANNING_PAGE',
  PATRIMONY_SCANNING: 'PATRIMONY_SCANNING_PAGE',
  PATRIMONY_DETAIL: 'PATRIMONY_DETAIL',
};

export default PAGES;
